[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing for subpages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404